// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWdV-QtN6d1rxLR5KVmdkOjdudc3xai28',
    appId: '1:772176384476:web:1e7743f8a9dd513bed3f19',
    messagingSenderId: '772176384476',
    projectId: 'ejemplo-firebasecybxs',
    authDomain: 'ejemplo-firebasecybxs.firebaseapp.com',
    storageBucket: 'ejemplo-firebasecybxs.firebasestorage.app',
    measurementId: 'G-LP22CYSE7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-i5kVRw4aFlWqs1x7IItSjRVi02m2Tac',
    appId: '1:772176384476:android:712fd727d6588562ed3f19',
    messagingSenderId: '772176384476',
    projectId: 'ejemplo-firebasecybxs',
    storageBucket: 'ejemplo-firebasecybxs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQm6xlTiSWpR2_OPdFgfaeTcf58Df3l-s',
    appId: '1:772176384476:ios:4df972cd008dfe99ed3f19',
    messagingSenderId: '772176384476',
    projectId: 'ejemplo-firebasecybxs',
    storageBucket: 'ejemplo-firebasecybxs.firebasestorage.app',
    androidClientId: '772176384476-nkbeuvhg1dmiuglbm52615b2fh16k4eb.apps.googleusercontent.com',
    iosClientId: '772176384476-p0opbbmpqt97e6q66tn13la9108unigl.apps.googleusercontent.com',
    iosBundleId: 'com.example.albumBiblio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQm6xlTiSWpR2_OPdFgfaeTcf58Df3l-s',
    appId: '1:772176384476:ios:4df972cd008dfe99ed3f19',
    messagingSenderId: '772176384476',
    projectId: 'ejemplo-firebasecybxs',
    storageBucket: 'ejemplo-firebasecybxs.firebasestorage.app',
    androidClientId: '772176384476-nkbeuvhg1dmiuglbm52615b2fh16k4eb.apps.googleusercontent.com',
    iosClientId: '772176384476-p0opbbmpqt97e6q66tn13la9108unigl.apps.googleusercontent.com',
    iosBundleId: 'com.example.albumBiblio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWdV-QtN6d1rxLR5KVmdkOjdudc3xai28',
    appId: '1:772176384476:web:535fa74854635244ed3f19',
    messagingSenderId: '772176384476',
    projectId: 'ejemplo-firebasecybxs',
    authDomain: 'ejemplo-firebasecybxs.firebaseapp.com',
    storageBucket: 'ejemplo-firebasecybxs.firebasestorage.app',
    measurementId: 'G-YWQ3XRNTDQ',
  );

}